-- task_4.sql
-- Prints column details for 'books' in the CURRENT database (passed via mysql cmd).
SELECT
  COLUMN_NAME   AS 'FIELD',
  COLUMN_TYPE   AS 'TYPE',
  IS_NULLABLE   AS 'NULL',
  COLUMN_KEY    AS 'KEY',
  COLUMN_DEFAULT AS 'DEFAULT',
  EXTRA         AS 'EXTRA'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'books'
ORDER BY ORDINAL_POSITION;
